repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.8.0
  hooks:
      - id: pyupgrade
        args: [--py310-plus]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
      - id: end-of-file-fixer
        exclude: changelog/
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
- repo: https://github.com/python-poetry/poetry
  rev: 1.5.1
  hooks:
      - id: poetry-check
        language_version: python3.12
      - id: poetry-lock
        args: ["--check"]
        language_version: python3.12
- repo: https://github.com/frostming/fix-future-annotations
  rev: 0.5.0
  hooks:
      - id: fix-future-annotations
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.5
  hooks:
      - id: ruff
      - id: ruff
        args: [ --select, I, --fix ]
      - id: ruff-format
